#!/usr/bin/env python3
"""Generate 3 CSV + 3 XLSX sample vocab files (stdlib only)."""

from __future__ import annotations

import csv
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

OUT_DIR = Path(__file__).resolve().parent

HEADER = ["Word", "Pronunciation", "Meaning", "Description", "ExampleSentence"]

SETS = {
    "ielts_academic_10": [
        ("meticulous", "/məˈtɪkjələs/", "Tỉ mỉ, cẩn thận", "Showing great attention to detail", "She is meticulous about her research notes."),
        ("ambiguous", "/æmˈbɪɡjuəs/", "Mơ hồ, không rõ ràng", "Open to more than one interpretation", "The contract wording is ambiguous."),
        ("coherent", "/koʊˈhɪrənt/", "Mạch lạc, logic", "Logical and consistent", "He presented a coherent argument."),
        ("feasible", "/ˈfiːzəbl/", "Khả thi", "Possible and practical to do", "The plan is feasible within our budget."),
        ("inevitable", "/ɪnˈevɪtəbl/", "Không thể tránh", "Certain to happen", "Change is inevitable in any industry."),
        ("scrutinize", "/ˈskruːtənaɪz/", "Xem xét kỹ", "Examine closely and critically", "Auditors scrutinize financial records."),
        ("substantial", "/səbˈstænʃl/", "Đáng kể", "Of considerable importance or size", "They made substantial progress."),
        ("undermine", "/ˌʌndərˈmaɪn/", "Làm suy yếu", "Weaken gradually", "Rumors can undermine public trust."),
        ("viable", "/ˈvaɪəbl/", "Khả thi (sống)", "Capable of working successfully", "Solar power is a viable alternative."),
        ("widespread", "/ˈwaɪdspred/", "Phổ biến rộng", "Found over a large area", "There is widespread support for reform."),
    ],
    "business_workplace_10": [
        ("deadline", "/ˈdedlaɪn/", "Hạn chót", "The latest time something must be done", "We must meet the project deadline."),
        ("negotiate", "/nɪˈɡoʊʃieɪt/", "Đàm phán", "Try to reach an agreement", "They negotiated a better contract."),
        ("revenue", "/ˈrevənuː/", "Doanh thu", "Income generated by business", "Revenue increased by twelve percent."),
        ("stakeholder", "/ˈsteɪkhoʊldər/", "Bên liên quan", "Person with an interest in a company", "Stakeholders approved the merger."),
        ("invoice", "/ˈɪnvɔɪs/", "Hóa đơn", "A bill for goods or services", "Please send the invoice by Friday."),
        ("leverage", "/ˈlevərɪdʒ/", "Tận dụng lợi thế", "Use something to maximum advantage", "We can leverage our brand reputation."),
        ("compliance", "/kəmˈplaɪəns/", "Tuân thủ", "Acting according to rules", "Compliance training is mandatory."),
        ("scalable", "/ˈskeɪləbl/", "Có thể mở rộng", "Able to grow without losing quality", "The platform is highly scalable."),
        ("benchmark", "/ˈbentʃmɑːrk/", "Chuẩn so sánh", "A standard for comparison", "We benchmark against industry leaders."),
        ("onboarding", "/ˈɑːnbɔːrdɪŋ/", "Tiếp nhận nhân sự", "Integrating a new employee", "Onboarding takes two weeks."),
    ],
    "travel_tourist_10": [
        ("itinerary", "/aɪˈtɪnəreri/", "Lịch trình", "A planned route or journey", "Our itinerary includes Kyoto and Osaka."),
        ("accommodation", "/əˌkɑːməˈdeɪʃn/", "Chỗ ở", "A place to stay", "We booked accommodation near the beach."),
        ("boarding pass", "/ˈbɔːrdɪŋ pæs/", "Thẻ lên máy bay", "A document allowing you to board", "Show your boarding pass at the gate."),
        ("customs", "/ˈkʌstəmz/", "Hải quan", "Government agency controlling imports", "We waited in line at customs."),
        ("layover", "/ˈleɪoʊvər/", "Dừng chân (bay)", "A stop between flights", "We have a six-hour layover in Dubai."),
        ("souvenir", "/ˌsuːvəˈnɪr/", "Quà lưu niệm", "Something kept as a reminder", "She bought a souvenir from the market."),
        ("excursion", "/ɪkˈskɜːrʒn/", "Chuyến tham quan", "A short journey for pleasure", "The hotel offers a city excursion."),
        ("reservation", "/ˌrezərˈveɪʃn/", "Đặt chỗ", "An arrangement to keep something", "I made a dinner reservation online."),
        ("backpack", "/ˈbækpæk/", "Ba lô", "A bag carried on the back", "Pack light and use a small backpack."),
        ("jet lag", "/ˈdʒet læɡ/", "Lệch múi giờ", "Fatigue after a long flight", "I always get jet lag after long flights."),
    ],
}


def col_letter(index: int) -> str:
    result = ""
    n = index
    while True:
        result = chr(65 + (n % 26)) + result
        n = n // 26 - 1
        if n < 0:
            break
    return result


def cell_xml(row: int, col: int, value: str) -> str:
    ref = f"{col_letter(col)}{row}"
    text = escape(value)
    return (
        f'<c r="{ref}" t="inlineStr"><is><t>{text}</t></is></c>'
    )


def sheet_xml(rows: list[list[str]]) -> str:
    sheet_rows = []
    for r_idx, row in enumerate(rows, start=1):
        cells = "".join(cell_xml(r_idx, c_idx, val) for c_idx, val in enumerate(row))
        sheet_rows.append(f'<row r="{r_idx}">{cells}</row>')
    rows_xml = "".join(sheet_rows)
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        f"<sheetData>{rows_xml}</sheetData></worksheet>"
    )


def write_xlsx(path: Path, rows: list[tuple]) -> None:
    all_rows = [HEADER] + [list(r) for r in rows]
    sheet = sheet_xml(all_rows)
    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>"""
    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""
    workbook = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
 xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="Vocabulary" sheetId="1" r:id="rId1"/></sheets>
</workbook>"""
    workbook_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>"""

    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("xl/workbook.xml", workbook)
        zf.writestr("xl/_rels/workbook.xml.rels", workbook_rels)
        zf.writestr("xl/worksheets/sheet1.xml", sheet)


def write_csv(path: Path, rows: list[tuple]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(HEADER)
        writer.writerows(rows)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for base, rows in SETS.items():
        write_csv(OUT_DIR / f"{base}.csv", rows)
        write_xlsx(OUT_DIR / f"{base}.xlsx", rows)
        print(f"OK {base}.csv / {base}.xlsx ({len(rows)} words)")


if __name__ == "__main__":
    main()
